// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace Signalizer.Models;

public partial class SignalType
{
    public long Id { get; set; }

    [Key]
    public int Key { get; set; }

    public string Value { get; set; }

    public virtual ICollection<TradingSignal> TradingSignals { get; set; } = new List<TradingSignal>();
}