// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Signalizer.Models;

public partial class UserSignalStrategy
{
    public long Id { get; set; }

    public string UserId { get; set; }

    public long StrategyId { get; set; }

    public virtual SignalStrategy Strategy { get; set; }
}